import { describe, expect, test } from "bun:test";
import { MAX_CURSOR_BYTES, MAX_CONNECTION_STATE_BYTES, validateEventInput, type OAuthTransport } from "@kizuki/core";
import { createGmailConnector, GMAIL_SCOPES } from "../src/index";
import { GmailFixture } from "../src/testing";
import { FIELDS } from "../src/state";
const config = { client: { id: "synthetic-desktop-client" }, secret_ref: "file:synthetic", fields: FIELDS };
describe("Gmail public connector", () => {
    test("missing registered application refuses before browser, resolver or state write", async () => {
        const connector = createGmailConnector({});
        let calls = 0;
        const touch = async () => { calls++; return ""; };
        await expect(connector.connect(touch)).rejects.toMatchObject({ code: "misconfigured" });
        await expect(connector.signIn!({ prompt: touch, notify: () => { calls++; }, openUrl: async () => { calls++; } }, { write: async () => { calls++; } })).rejects.toMatchObject({ code: "misconfigured" });
        expect(calls).toBe(0);
        expect((await connector.health()).state).toBe("misconfigured");
        expect(GMAIL_SCOPES).toEqual(["openid", "email", "https://www.googleapis.com/auth/gmail.readonly"]);
    });
    test("bounded snapshots replay stably and never download attachments", async () => {
        const fixture = new GmailFixture(45);
        const connector = await fixture.connected();
        const first = await connector.backfill(null);
        expect(first.events).toHaveLength(20);
        expect(first.events.every(event => validateEventInput(event).ok)).toBe(true);
        expect((await connector.backfill(null)).events).toEqual(first.events);
        expect(Buffer.byteLength(first.cursor!)).toBeLessThanOrEqual(MAX_CURSOR_BYTES);
        expect(fixture.state.byteLength).toBeLessThan(MAX_CONNECTION_STATE_BYTES);
        expect(new TextDecoder().decode(fixture.state)).not.toContain("Synthetic message body");
        const resumed = await fixture.connected();
        const second = await resumed.backfill(first.cursor);
        expect(second.events).toHaveLength(20);
        expect(new Set([...first.events, ...second.events].map(e => e.source_record_id)).size).toBe(40);
        expect(fixture.requests.every(url => !url.includes("/attachments/"))).toBe(true);
    });
    test("only explicit history deletion emits an observation-time tombstone", async () => {
        const fixture = new GmailFixture(2);
        const connector = await fixture.connected();
        const snapshot = await connector.backfill(null);
        fixture.change("m1", "labelsRemoved");
        fixture.change("m2", "messagesDeleted");
        const changes = await connector.sync(snapshot.cursor);
        expect(changes.events).toHaveLength(2);
        const tombstone = changes.events.find(event => event.deleted)!;
        expect(tombstone.source_record_id).toBe(snapshot.events[1]!.source_record_id);
        expect(tombstone.text).toBe("");
        expect(tombstone.metadata.provider_deleted_at).toBeNull();
        expect(tombstone.metadata.occurred_at_semantics).toBe("deletion_observed");
        expect(tombstone.occurred_at).toBe(tombstone.observed_at);
        fixture.advanceDay();
        const reopened = await fixture.connected();
        expect((await reopened.sync(snapshot.cursor)).events).toEqual(changes.events);
    });
    test("lost message GET and expired history never infer deletion from absence", async () => {
        const fixture = new GmailFixture(1);
        const connector = await fixture.connected();
        const before = await connector.backfill(null);
        fixture.change("m1", "labelsAdded");
        fixture.missing.add("m1");
        const missing = await connector.sync(before.cursor);
        expect(missing.events).toEqual([]);
        expect(missing.detail).toContain("message_unavailable");
        fixture.expired = true;
        const gap = await connector.sync(missing.cursor);
        expect(gap.events.every(event => !event.deleted)).toBe(true);
        expect(gap.detail).toContain("history_gap");
    });
    test("account mismatch and revoked session refuse without captured output", async () => {
        const fixture = new GmailFixture(1);
        fixture.account = "different-account";
        await expect(fixture.connected()).rejects.toMatchObject({ code: "unauthenticated" });
        fixture.account = "fixture-account";
        const connector = await fixture.connected();
        await connector.revoke();
        await expect(connector.sync(null)).rejects.toMatchObject({ code: "unauthenticated" });
        expect((await connector.health()).state).toBe("disabled");
    });
    test("provider auth rejection during message capture reports unauthenticated health", async () => {
        const fixture = new GmailFixture(2);
        const oauth: OAuthTransport = { listen: async () => { throw new Error("not used"); }, postForm: async () => ({ status: 200, body: { access_token: "synthetic-rotated-access-not-a-credential", refresh_token: "synthetic-rotated-refresh-not-a-credential", expires_in: 3600, scope: GMAIL_SCOPES.join(" "), token_type: "Bearer" } }) };
        let rejectMessage = true;
        const connector = createGmailConnector(config, { persist: fixture.persist, now: fixture.now, oauth, fetch: async (request) => rejectMessage && request.url.includes("/messages/m2?") ? Response.json({ error: "SECRET_SENTINEL" }, { status: 401 }) : fixture.fetch(request) });
        await connector.connect(async () => new TextDecoder().decode(fixture.state));
        const failed = await connector.backfill(null);
        expect(failed.status).toBe("unavailable");
        expect(failed.events).toEqual([]);
        expect(failed.cursor).toBeNull();
        expect(failed.detail).toContain("unauthenticated");
        expect(JSON.stringify(failed)).not.toContain("SECRET_SENTINEL");
        expect((await connector.health()).state).toBe("unauthenticated");
        rejectMessage = false;
        const recovered = await connector.backfill(null);
        expect(recovered.status).not.toBe("unavailable");
        expect(recovered.events.map(event => event.metadata.message_id)).toEqual(["m1", "m2"]);
    });
    test("a rejected grant during message capture fences the instance without advancing", async () => {
        const fixture = new GmailFixture(2);
        const connector = createGmailConnector(config, { persist: fixture.persist, now: fixture.now, oauth: { listen: async () => { throw new Error("not used"); }, postForm: async () => ({ status: 400, body: { error: "invalid_grant", error_description: "SECRET_SENTINEL" } }) }, fetch: async (request) => request.url.includes("/messages/m2?") ? Response.json({ error: "SECRET_SENTINEL" }, { status: 401 }) : fixture.fetch(request) });
        await connector.connect(async () => new TextDecoder().decode(fixture.state));
        const refused = await connector.backfill(null);
        expect(refused.status).toBe("unavailable");
        expect(refused.events).toEqual([]);
        expect(refused.cursor).toBeNull();
        expect(refused.detail).toContain("unauthenticated");
        expect(refused.detail).not.toContain("SECRET_SENTINEL");
        expect((await connector.health()).state).toBe("unauthenticated");
        await expect(connector.backfill(null)).rejects.toMatchObject({ code: "unavailable" });
    });
    test("provider error text and malformed cursors never escape or move checkpoint", async () => {
        const fixture = new GmailFixture(1);
        const connector = await fixture.connected();
        const cursor = (await connector.backfill(null)).cursor;
        fixture.failStatus = 429;
        const failed = await connector.sync(cursor);
        expect(failed.status).toBe("unavailable");
        expect(failed.cursor).toBe(cursor);
        expect(JSON.stringify(failed)).not.toContain("SECRET_SENTINEL");
        await expect(connector.sync(" ".repeat(MAX_CURSOR_BYTES + 1))).rejects.toMatchObject({ code: "source_schema" });
    });
});
