/** Invented receipt data for refusal tests. Never runtime or release evidence. */
import { createHash } from "node:crypto";
import { RAIL_IDS } from "../packages/core/src/serve/types";
import { CURRENT_PACKAGE_FILES } from "./release-artifacts";
import { SQLITE_ENGINE_POLICY } from "./artifact-proof";
import { LIFECYCLE_BASELINE_SOURCE, LIFECYCLE_HISTORY, LIFECYCLE_MODEL_IDS, LIFECYCLE_ORIGINAL_STEPS, LIFECYCLE_RECOVERY_IDS, LIFECYCLE_REGISTRY_SHA256, LIFECYCLE_STATE_IDS, type NativeLifecycleIdentity } from "./native-lifecycle-proof";
const h=(s:string)=>createHash("sha256").update(s).digest("hex");
export function lifecycleFixture(expected: NativeLifecycleIdentity): any {
  const mac=expected.target.includes("darwin"), unit=(name:string)=>mac?`dev.kizuki.${name}`:`kizuki@${name}.service`;
  const active=(name:string)=>({manager_pid:101,marker_pid:101,instance_id:name,command:"synthetic executable"});
  const command={exit_code:0,stdout:"synthetic observatory",stderr:""};
  const steps:any[]=LIFECYCLE_ORIGINAL_STEPS.map(id=>({id,passed:true,evidence:{...command}}));
  const set=(id:string,evidence:any)=>steps.find(s=>s.id===id).evidence=evidence;
  for(const id of ["default-init-running","repeat-install-replaces-process","crash-restarts-new-instance","replacement-executable-running","rollback-restores-replacement-process"])set(id,active(id));
  set("private-unit",{unit:unit("original"),mode:384,sha256:h("unit")});
  set("deliberately-stopped",{unit_exists:false,intent:"opted-out"});
  set("native-api-failed-activation-rolls-back",{failure:"synthetic expected activation failure",unit_sha256:h("unit"),recovery_journal_exists:false,boundary:"synthetic native activation rollback"});
  set("installed-rails-healthy",{exit_code:0,doctor_ok:true,canon_writing:"off",failures:[],identity_degraded:[],rails:RAIL_IDS.map(rail=>({rail,status:"ok",reason:null})),diagnostics:{complete:true,truncated:false,error:null,receipts:RAIL_IDS.map(rail=>({rail,status:"ok",finished_at:"2026-09-07T00:01:02Z",current_instance:true,errors:[],retrieval_degraded:[]}))}});
  steps.splice(steps.findIndex(s=>s.id==="uninstall-before-stopped-read"),0,{id:mac?"launchd-graceful-exit":"systemd-graceful-exit",passed:true,evidence:{...command}});
  if(mac)steps.splice(steps.findIndex(s=>s.id==="crash-restarts-new-instance"),0,{id:"uninstrumented-repeat-install",passed:true,evidence:{...command}},{id:"repeat-install-replaces-process",passed:true,evidence:active("uninstrumented")});
  set("native-user-manager-available",{command:mac?"launchctl print gui/<uid>":"systemctl --user show --property=Version",exit_code:0});
  set("default-init-installs-service",{...command,instrumented:mac,timing_changed:mac,native_status:null});
  set("public-status-agrees-with-native-manager",{...command,stdout:JSON.stringify({data:{pid:101,supervisor:{state:"active",enabled:true}}})});
  for(const id of ["public-graceful-stop","uninstall-before-stopped-read","stopped-import","replacement-location-install","final-uninstall","export-stopped-vault","verify-recovery-export","restore-stopped-vault","uninstrumented-repeat-install"])if(steps.some(s=>s.id===id))set(id,{...command,command:["kizuki","synthetic-command"]});
  set("repeat-install",mac?{...command,instrumented:true,timing_changed:true}:{...command,command:["kizuki","serve","--install"]});
  if(mac)set("launchd-graceful-exit",{operation:"print",exit_code:0,signal:null,duration_ms:0,state:"running",pid:101,last_exit_code:0,error:null,output_truncated:false});
  else set("systemd-graceful-exit",{...command,stdout:"ExecMainStatus=0"});
  const prior=Object.fromEntries(CURRENT_PACKAGE_FILES.map(name=>[name,h(`prior:${name}`)]));
  const engine=SQLITE_ENGINE_POLICY.accepted[0],runtime={schema:"kizuki.sqlite-runtime/v1",bun_version:"1.3.14",sqlite_version:engine.sqlite_version,sqlite_source_id:engine.sqlite_source_id};
  const baseline={source_sha:LIFECYCLE_BASELINE_SOURCE,target:expected.target,bun_version:"1.3.14",package_sha256:prior,runtime:{kizuki:{executable_sha256:prior.kizuki,runtime,exit_code:0,doctor_status:"ok"},kizuki_mcp:{executable_sha256:prior["kizuki-mcp"],runtime,exit_code:0,mcp_is_error:false}}};
  const phases:any[]=LIFECYCLE_STATE_IDS.map(id=>{
    const initial=id==="init-no-service",missing=id==="state-missing",failed=id==="state-failed",masked=id==="state-masked",exists=!initial&&!missing;
    return {id,passed:true,evidence:{mechanism:mac?(masked?"not-applicable-launchd":"launchd"):"systemd",unit:unit(failed?"failed-state":"states"),unit_state:masked?(mac?"not-applicable":"masked"):"absent",manager_exit:0,manager_pid:null,definition_exists:exists,intent:initial?"opted-out":"installed",public_supervisor_state:initial||missing?"absent":masked&&!mac?"masked":"disabled",public_enabled:failed,public_detail:failed?"failed":"absent",public_doctor_ok:initial,observed_failure:failed?"synthetic failure":null,process_absent:true,definition_sha256:exists&&!(masked&&!mac)?h("definition"):null}};
  });
  phases.push({id:"cross-binary-upgrade",passed:true,evidence:{baseline_source_sha:LIFECYCLE_BASELINE_SOURCE,candidate_source_sha:expected.source_sha,baseline_binary_sha256:prior.kizuki,candidate_binary_sha256:expected.package_sha256.kizuki,baseline_schema:21,candidate_schema:21,baseline_instance_id:"prior-instance",candidate_instance_id:"current-instance",baseline_pid:110,candidate_pid:111,vault_id:"upgrade-vault",before_event_sha256:h("event"),after_event_sha256:h("event"),baseline_stopped:true,candidate_active:true,baseline_query_preserved:true,candidate_query_preserved:true,backup_verified:true,backup_manifest_sha256:h("backup"),unit_sha256:h("upgrade-unit"),unit:unit("upgrade")}});
  const snap=(schema:number,claims=0)=>({schema_version:schema,schema_sha256:h(`schema${schema}`),rows_sha256:h(`rows${schema}:${claims}`),files_sha256:h("sentinel"),table_count:25,row_count:30,events:1,claims,integrity:"ok",foreign_key_errors:0});
  for(const id of LIFECYCLE_RECOVERY_IDS){
    const failure=id==="migration-failure-preserved",restore=id.startsWith("restore-"),fixture=LIFECYCLE_HISTORY[id==="migrate-ledger16"?1:id==="restore-backup16"?2:id==="restore-claim-backup16"?3:0]!,claims=fixture.id.includes("claim")||fixture.id==="ledger16"?1:0;
    const roles=failure?["admission-before","admission-after","late-ddl-before","late-ddl-after"]:restore?["restored"]:[id==="migration-backup-recovery"?"recovery-preimage":"before","doctor-after","migrated"];
    const commands=(failure?["initialize","migrate","initialize","migrate"]:restore?["restore-verify","restore","rebuild","query"]:["initialize","doctor-before","migrate","rebuild","query"]).map(step=>{const denied=step==="doctor-before"||failure&&step==="migrate";return {step,argv:["kizuki",step,"$WORKSPACE/synthetic"],expected_exit:denied?1:0,exit_code:denied?1:0,signal:null,duration_ms:1,stdout_sha256:h("out"),stderr_sha256:h("err"),diagnostic:denied?(step==="doctor-before"?"migration_required":"migration_rejected"):"none"};});
    phases.push({id,passed:true,evidence:{fixture_id:fixture.id,fixture_sha256:fixture.sha256,writer_commit:fixture.writer_commit,writer_bun:fixture.writer_bun,candidate_source_sha:expected.source_sha,helper_source_sha:expected.source_sha,executable_sha256:expected.package_sha256.kizuki,commands,snapshots:roles.map(role=>({role,value:snap(role==="migrated"||role==="restored"?21:fixture.ledger,claims)})),preservation:{events:failure?0:1,claims:failure?0:claims,event_sha256:h("event"),claim_sha256:h("claim"),original_columns_equal:!failure,current_claim_consumer:!failure&&claims?"passed":"not_applicable",public_query:failure?"not_run":"passed"},recovery_copy_sha256:fixture.id==="ledger15"?h("recovery-copy"):null,failure_scope:failure?"admission-and-late-ddl-transaction-rollback":"none",retained_failed_vaults:failure?["failed-admission","failed-late-ddl"]:[],failure_code:null}});
  }
  for(const id of LIFECYCLE_MODEL_IDS){const absent=id==="model-absent",loss=id==="model-credential-loss",configured=id==="model-configured",offline=id==="model-dependency-offline";
    const evidence:any={unit:unit(id),instance_id:id,pid:120,started_at:"2026-09-07T00:01:02Z",receipt_run_id:`run-${id}`,receipt_status:absent||configured?"ok":"failed",model_calls:absent||loss?0:1,model_unavailable:absent||configured||loss?0:1,claims_extracted:configured?1:0,canon_writes:configured?1:0,endpoint_requests:configured||id==="model-unavailable"?1:0,unexpected_requests:0,credential_present:!absent&&!loss,model_configured:!absent,source_event_present:true,query_preserved:true,weights_unchanged:true,config_unchanged:true,configuration_unavailable:loss,daemon_active:true,model_ref_sha256:absent?null:h(id),model_claims:configured?1:0,model_canon_receipts:configured?1:0,model_output_readable:configured,recovery:null};
    if(offline)evidence.recovery={trigger:"service-restart",stop_confirmed:true,receipt_trigger:"scheduled",receipt_due_at:"2026-09-07T00:01:02.000Z",scheduling_override:{rail:"sync",old:null,next:"2026-09-07T00:01:02.000Z",reason:"synthetic-due-time-for-recovery"},unit:evidence.unit,pid:121,instance_id:"offline-recovered",started_at:"2026-09-07T00:01:03Z",receipt_run_id:"run-recovered",receipt_status:"ok",model_calls:1,model_unavailable:0,claims_extracted:1,canon_writes:1,endpoint_requests:1,unexpected_requests:0,model_claims:1,model_canon_receipts:1,model_output_readable:true,source_event_present:true,query_preserved:true,daemon_active:true,config_unchanged:true,credential_unchanged:true,endpoint_unchanged:true};
    phases.push({id,passed:true,evidence});
  }
  const recovery_services=LIFECYCLE_RECOVERY_IDS.filter(id=>id!=="migration-failure-preserved").map(id=>({id,vault_id:`vault-${id}`,unit:unit(id),pid:130,instance_id:`instance-${id}`,ledger_schema:21,active:true,stopped:true,event_text_sha256:h("event")}));
  const units=new Set([unit("original"),...phases.filter(p=>p.evidence.unit).map(p=>p.evidence.unit),...recovery_services.map(s=>s.unit)]);
  return {schema:"kizuki.native-service-lifecycle/v2",source_sha:expected.source_sha,target:expected.target,host:{platform:mac?"darwin":"linux",arch:mac?"arm64":"x64",kernel:"synthetic",bun:"1.3.14",uid:1000},binary_sha256:expected.package_sha256.kizuki,package_sha256:expected.package_sha256,steps,failures:[],scope:{native_user_service:true,synthetic_vault_only:true,release_upgrade:false,migration_rollback:true,configured_model:true,cross_binary_fixture_upgrade:true,historical_migration:true,configured_synthetic_model:true,dependency_offline_startup:true,hardware_reboot:false,host_network_isolation:false},qualification:{registry_sha256:LIFECYCLE_REGISTRY_SHA256,baseline,phases,recovery_services},passed:true,cleanup:{attempted:true,service_gone:true,unit_removed:true,synthetic_root_removed:true,units:[...units].map(unit=>({unit,service_gone:true,unit_removed:true}))}};
}
